services:
  taskbroker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'taskbroker-data:/opt/'
    ports:
    - "50051:50051"
    networks:
      - sentry

volumes:
  # These store application data that should persist across restarts.
  taskbroker-data:

networks:
  sentry:
    name: sentry
    external: true
