preReleaseCommand: ../scripts/bump-version-clients.sh

changelog:
  policy: auto

targets:
  - name: github
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi

requireNames:
  - /.*taskbroker_client.*whl$/
  - /.*taskbroker_client.*tar\.gz$/
