apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskworker
  labels:
    app: taskworker
spec:
  replicas: 8
  selector:
    matchLabels:
      app: taskworker
  template:
    metadata:
      labels:
        app: taskworker
    spec:
      containers:
        - name: taskworker-container
          image: us-central1-docker.pkg.dev/sentryio/taskworker/image@sha256:3ba1c93419eb1cb2a6fc40028f6fac1085b7d5d9956aaae1d9f7b827a5de9291
          env:
            - name: SENTRY_TASKWORKER_GRPC_HOST
              value: "taskbroker-service"
            - name: SENTRY_TASKWORKER_GRPC_PORT
              value: "50051"
            - name: SENTRY_TASKWORKER_NAMESPACE
              value: "test"
            - name: SENTRY_TASKWORKER_FAILURE_RATE
              value: "0.0"
            - name: SENTRY_TASKWORKER_TIMEOUT_RATE
              value: "0.0"
          ports:
            - containerPort: 8686
