apiVersion: v1
kind: Service
metadata:
  name: taskbroker-service
  labels:
    app: taskbroker-service
spec:
  ports:
  - port: 50051
    name: grpc
  clusterIP: None
  selector:
    app: taskbroker
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400 # default is 10800
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: taskbroker
spec:
  selector:
    matchLabels:
      app: taskbroker # has to match .spec.template.metadata.labels
  serviceName: "taskbroker"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: taskbroker # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: taskbroker
        image: us-central1-docker.pkg.dev/sentryio/taskbroker/image:8ff9bdee7be16ecf73bc9a20a7db6f2d9dda2e95
        env:
          - name: TASKBROKER_KAFKA_CLUSTERS__DEFAULT__ADDRESS
            value: "kafka-001:9092"
          - name: TASKBROKER_KAFKA_TOPICS__TASKWORKER__CLUSTER
            value: "default"
          - name: TASKBROKER_KAFKA_TOPICS__TASKWORKER__CONSUMER_GROUP
            value: "taskworker"
          - name: TASKBROKER_KAFKA_DEADLETTER_TOPIC
            value: "taskworker_dlq"
          - name: TASKBROKER_KAFKA_TOPICS__TASKWORKER_DLQ__CLUSTER
            value: "default"
          - name: TASKBROKER_KAFKA_TOPICS__TASKWORKER_DLQ__CONSUMER_GROUP
            value: "taskworker"
          - name: TASKBROKER_KAFKA_TOPICS__TASKWORKER_DLQ__PRODUCE_ONLY
            value: "true"
        ports:
        - containerPort: 50051
          name: grpc
        volumeMounts:
        - name: sqlite
          mountPath: /opt/sqlite
  volumeClaimTemplates:
  - metadata:
      name: sqlite
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: taskbroker-sqlite
      resources:
        requests:
          storage: 100Mi
