from __future__ import annotations

import contextlib
import logging
import queue
import signal
import threading
import time
from collections.abc import Callable, Generator, Sequence
from dataclasses import dataclass
from functools import partial
from multiprocessing.synchronize import Event
from types import FrameType
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from multiprocessing.sharedctypes import Synchronized

# XXX: Don't import any modules that will import django here, do those within child_process
import msgpack
import sentry_sdk
import zstandard as zstd
from arroyo.backends.abstract import ProducerFuture
from arroyo.backends.kafka import KafkaPayload
from arroyo.types import BrokerValue
from sentry_protos.taskbroker.v1.taskbroker_pb2 import (
    TASK_ACTIVATION_STATUS_COMPLETE,
    TASK_ACTIVATION_STATUS_FAILURE,
    TASK_ACTIVATION_STATUS_RETRY,
    TaskActivation,
    TaskActivationStatus,
)
from sentry_sdk.consts import OP, SPANDATA, SPANSTATUS
from sentry_sdk.crons import MonitorStatus, capture_checkin

from taskbroker_client.app import import_app
from taskbroker_client.constants import CompressionType
from taskbroker_client.retry import NoRetriesRemainingError
from taskbroker_client.state import clear_current_task, current_task, set_current_task
from taskbroker_client.task import Task
from taskbroker_client.types import ContextHook, InflightTaskActivation, ProcessingResult
from taskbroker_client.worker.producer import TaskProducer

logger = logging.getLogger(__name__)


class ProcessingDeadlineExceeded(BaseException):
    pass


@dataclass
class ActivationWithPendingFutures:
    """
    Represents an executed inflight activation that
    produced messages, and is pending results from the producer
    futures.

    Args:
        inflight: The inflight activation.
        status: The status of the activation after execution.
        execution_start_time: Timestamp of task execution start.
        futures_start_time: Timestamp of when the pending futures were enqueued.
        pending_futures: Set of pending futures generated by executing this activation.
        task_func: The Task object related to this activation.
    """

    inflight: InflightTaskActivation
    status: TaskActivationStatus.ValueType
    execution_start_time: float
    futures_start_time: float
    pending_futures: dict[str, set[ProducerFuture[BrokerValue[KafkaPayload]]]]
    task_func: Task[Any, Any]


@contextlib.contextmanager
def timeout_alarm(
    seconds: int, handler: Callable[[int, FrameType | None], None]
) -> Generator[None]:
    """
    Context manager to handle SIGALRM handlers

    To prevent tasks from consuming a worker forever, we set a timeout
    alarm that will interrupt tasks that run longer than
    their processing_deadline.
    """
    original = signal.signal(signal.SIGALRM, handler)
    try:
        signal.alarm(seconds)
        yield
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, original)


def load_parameters(activation: TaskActivation) -> dict[str, Any]:
    headers = dict(activation.headers)
    compression_type = headers.get("compression-type", None)

    data = activation.parameters_bytes
    if compression_type == CompressionType.ZSTD.value:
        data = zstd.decompress(data)
    return msgpack.unpackb(data, raw=False)


def status_name(status: TaskActivationStatus.ValueType) -> str:
    """Convert a TaskActivationStatus to a human readable name"""
    if status == TASK_ACTIVATION_STATUS_COMPLETE:
        return "complete"
    if status == TASK_ACTIVATION_STATUS_FAILURE:
        return "failure"
    if status == TASK_ACTIVATION_STATUS_RETRY:
        return "retry"
    return f"unknown-{status}"


def _task_failure_extra(
    activation: TaskActivation,
    err: BaseException,
    processing_pool_name: str,
) -> dict[str, Any]:
    return {
        "task_id": activation.id,
        "taskname": activation.taskname,
        "namespace": activation.namespace,
        "processing_pool": processing_pool_name,
        "exception_type": type(err).__name__,
        "exception_message": str(err),
    }


def _log_task_failed(
    activation: TaskActivation,
    err: BaseException,
    processing_pool_name: str,
) -> None:
    """
    Emit a structured failure log via logger.exception. When the embedding
    application has the Sentry SDK's LoggingIntegration enabled (default),
    this also produces the Sentry event, so the same call covers both the
    structured stdout log and the Sentry capture. Call this from inside an
    existing isolation_scope block so fingerprints/tags are preserved.
    """
    logger.exception(
        "taskworker.task.failed",
        extra=_task_failure_extra(activation, err, processing_pool_name),
    )


def _log_task_retry_exhausted(
    activation: TaskActivation,
    err: BaseException,
    processing_pool_name: str,
) -> None:
    """
    Emit a structured retry-exhausted log without logger.exception so the
    explicit NoRetriesRemainingError capture remains the only Sentry error
    event from this branch.
    """
    logger.warning(
        "taskworker.task.retry_exhausted",
        extra={
            **_task_failure_extra(activation, err, processing_pool_name),
            "retry_attempts": activation.retry_state.attempts,
            "retry_max_attempts": activation.retry_state.max_attempts,
        },
    )


def _adjust_busy(counter: "Synchronized[int] | None", delta: int) -> None:
    """
    Adjust the shared count of children currently executing a task.

    The parent worker pool divides this by concurrency to emit occupancy, the
    autoscaling signal. A child that is hard-killed (e.g. OOM) mid-task leaks
    its increment; the parent clamps occupancy to [0, 1] to bound the drift.
    """
    if counter is None:
        return
    with counter.get_lock():
        counter.value += delta


def child_process(
    app_module: str,
    child_tasks: queue.Queue[InflightTaskActivation],
    processed_tasks: queue.Queue[ProcessingResult],
    shutdown_event: Event,
    max_task_count: int | None,
    processing_pool_name: str,
    process_type: str,
    skip_awaiting_futures: bool,
    ready_counter: "Synchronized[int] | None" = None,
    busy_counter: "Synchronized[int] | None" = None,
) -> None:
    """
    The entrypoint for spawned worker children.

    Any import that could pull in django needs to be put inside this functiona
    and not the module root. If modules that include django are imported at
    the module level the wrong django settings will be used.
    """
    app = import_app(app_module)
    app.load_modules()
    metrics = app.metrics
    # Signals when the parent worker pool terminates the child
    local_shutdown = threading.Event()

    def handle_sigterm(*args: Any) -> None:
        logger.info(
            "taskworker.worker.sigterm_received",
            extra={"processing_pool": processing_pool_name},
        )
        local_shutdown.set()

    signal.signal(signal.SIGTERM, handle_sigterm)
    signal.signal(signal.SIGINT, signal.SIG_IGN)

    def _get_known_task(activation: TaskActivation) -> Task[Any, Any] | None:
        try:
            namespace = app.get_namespace(activation.namespace)
        except KeyError:
            logger.error(
                "taskworker.invalid_namespace",
                extra={"namespace": activation.namespace, "taskname": activation.taskname},
            )
            return None

        if not namespace.contains(activation.taskname):
            logger.error(
                "taskworker.invalid_taskname",
                extra={"namespace": activation.namespace, "taskname": activation.taskname},
            )
            return None
        return namespace.get(activation.taskname)

    def run_worker(
        child_tasks: queue.Queue[InflightTaskActivation],
        processed_tasks: queue.Queue[ProcessingResult],
        shutdown_event: Event,
        max_task_count: int | None,
        processing_pool_name: str,
        process_type: str,
        skip_awaiting_futures: bool,
    ) -> None:
        processed_task_count = 0
        pending_task_futures: list[ActivationWithPendingFutures] = []

        def handle_alarm(signum: int, frame: FrameType | None) -> None:
            """
            Handle SIGALRM

            If we hit an alarm in a child, we need to push a result
            and terminate the child.
            """
            deadline = -1
            current = current_task()
            taskname = "unknown"
            if current:
                taskname = current.taskname
                deadline = current.processing_deadline_duration
            raise ProcessingDeadlineExceeded(
                f"execution deadline of {deadline} seconds exceeded by {taskname}"
            )

        def await_task_futures(task: ActivationWithPendingFutures) -> None:
            """
            Blocks on the result of each producer futures in the given task.
            If any futures raise an exception, the task is considered failed
            and submitted for retry (if the policy allows).
            """
            RESULT_TIMEOUT_SEC = 1
            error_name: str = "N/A"
            try:
                # We don't care about the actual result value,
                # we just care if result() raises or not
                [f.result(RESULT_TIMEOUT_SEC) for fut in task.pending_futures.values() for f in fut]
                produce_status = "success"
            # If any pending producer futures failed, retry the task
            except Exception as e:
                task.status = TASK_ACTIVATION_STATUS_FAILURE
                if task.task_func.retry:
                    retry_state = task.inflight.activation.retry_state
                    if not task.task_func.retry.max_attempts_reached(retry_state):
                        task.status = TASK_ACTIVATION_STATUS_RETRY
                produce_status = "failure"
                error_name = type(e).__name__
            metrics.incr(
                "taskworker.worker.produce.result",
                tags={
                    "status": produce_status,
                    "processing_pool": processing_pool_name,
                    "error_name": error_name,
                },
            )
            pending_task_futures.remove(task)
            _task_execution_complete(
                inflight=task.inflight,
                next_state=task.status,
                execution_start_time=task.execution_start_time,
                execution_end_time=task.futures_start_time,
                task_func=task.task_func,
                futures_start_time=task.futures_start_time,
                passthrough=skip_awaiting_futures,
            )

        def get_oldest_pending_activation() -> ActivationWithPendingFutures | None:
            oldest: ActivationWithPendingFutures | None = None
            max_age = 0.0
            now = time.time()
            for task in pending_task_futures:
                age = now - task.futures_start_time
                if age > max_age:
                    max_age = age
                    oldest = task
            return oldest

        def check_task_future_completion(
            shutdown_event: Event, local_shutdown: threading.Event
        ) -> None:
            while not shutdown_event.is_set() and not local_shutdown.is_set():
                if len(pending_task_futures) > 0:
                    # Records how many activations with pending producer futures
                    # the worker child has. Only records when there are pending activations.
                    metrics.gauge(
                        "taskworker.worker.activations_with_pending_futures",
                        len(pending_task_futures),
                        tags={
                            "processing_pool": processing_pool_name,
                        },
                    )
                    for task in pending_task_futures.copy():
                        future_status = [
                            f.done() for fut in task.pending_futures.values() for f in fut
                        ]
                        if all(future_status):
                            await_task_futures(task)
                        else:
                            # How many futures are still pending in this task
                            metrics.distribution(
                                "taskworker.task.incomplete_futures",
                                len([f for f in future_status if not f]),
                                tags={
                                    "processing_pool": processing_pool_name,
                                    "namespace": task.inflight.activation.namespace,
                                    "taskname": task.inflight.activation.taskname,
                                },
                            )
                    # How long has the oldest pending task been sitting in the queue
                    if oldest := get_oldest_pending_activation():
                        metrics.distribution(
                            "taskworker.worker.oldest_pending_activation_age",
                            time.time() - oldest.futures_start_time,
                            tags={
                                "processing_pool": processing_pool_name,
                                "namespace": oldest.inflight.activation.namespace,
                                "taskname": oldest.inflight.activation.taskname,
                            },
                        )
                else:
                    time.sleep(0.1)

        _future_completion_thread = threading.Thread(
            name="check-future-completion",
            target=partial(check_task_future_completion, shutdown_event, local_shutdown),
            daemon=True,
        )
        _future_completion_thread.start()

        while not shutdown_event.is_set() and not local_shutdown.is_set():
            if max_task_count and processed_task_count >= max_task_count:
                metrics.incr(
                    "taskworker.worker.max_task_count_reached",
                    tags={"count": processed_task_count, "processing_pool": processing_pool_name},
                )
                logger.info(
                    "taskworker.max_task_count_reached", extra={"count": processed_task_count}
                )
                # Still set the shutdown signal to trigger shutdown of the future checker thread
                local_shutdown.set()
                break

            try:
                inflight = child_tasks.get(timeout=1.0)
            except queue.Empty:
                metrics.incr(
                    "taskworker.worker.child_task_queue_empty",
                    tags={"processing_pool": processing_pool_name},
                )
                continue

            task_func = _get_known_task(inflight.activation)
            if not task_func:
                metrics.incr(
                    "taskworker.worker.unknown_task",
                    tags={
                        "namespace": inflight.activation.namespace,
                        "taskname": inflight.activation.taskname,
                        "processing_pool": processing_pool_name,
                    },
                    sample_rate=1.0,
                )
                with sentry_sdk.isolation_scope() as scope:
                    scope.set_tag("taskname", inflight.activation.taskname)
                    scope.set_tag("namespace", inflight.activation.namespace)
                    scope.set_tag("processing_pool", processing_pool_name)
                    scope.set_extra("activation", str(inflight.activation))
                    scope.capture_message(
                        f"Unregistered task {inflight.activation.taskname} was not executed"
                    )

                processed_tasks.put(
                    ProcessingResult(
                        task_id=inflight.activation.id,
                        status=TASK_ACTIVATION_STATUS_FAILURE,
                        host=inflight.host,
                        receive_timestamp=inflight.receive_timestamp,
                    )
                )
                continue

            if task_func.at_most_once:
                if app.should_attempt_at_most_once(inflight.activation):
                    metrics.incr(
                        "taskworker.task.at_most_once.executed",
                        tags={
                            "namespace": inflight.activation.namespace,
                            "taskname": inflight.activation.taskname,
                            "processing_pool": processing_pool_name,
                        },
                    )
                else:
                    metrics.incr(
                        "taskworker.worker.at_most_once.skipped",
                        tags={
                            "namespace": inflight.activation.namespace,
                            "taskname": inflight.activation.taskname,
                            "processing_pool": processing_pool_name,
                        },
                    )
                    continue

            set_current_task(inflight.activation)

            next_state = TASK_ACTIVATION_STATUS_FAILURE
            # Use time.time() so we can measure against activation.received_at
            execution_start_time = time.time()
            _adjust_busy(busy_counter, 1)
            try:
                with timeout_alarm(inflight.activation.processing_deadline_duration, handle_alarm):
                    _execute_activation(task_func, inflight.activation, app.context_hooks)
                next_state = TASK_ACTIVATION_STATUS_COMPLETE
            except ProcessingDeadlineExceeded as err:
                if task_func.report_timeout_errors:
                    with sentry_sdk.isolation_scope() as scope:
                        scope.fingerprint = [
                            "taskworker.processing_deadline_exceeded",
                            inflight.activation.namespace,
                            inflight.activation.taskname,
                        ]
                        scope.set_transaction_name(inflight.activation.taskname)
                        _log_task_failed(inflight.activation, err, processing_pool_name)
                metrics.incr(
                    "taskworker.worker.processing_deadline_exceeded",
                    tags={
                        "processing_pool": processing_pool_name,
                        "namespace": inflight.activation.namespace,
                        "taskname": inflight.activation.taskname,
                    },
                )
                retry = task_func.retry
                if retry and retry.should_retry(inflight.activation.retry_state, err):
                    next_state = TASK_ACTIVATION_STATUS_RETRY
                else:
                    next_state = TASK_ACTIVATION_STATUS_FAILURE
            except Exception as err:
                retry = task_func.retry
                captured_error = False
                should_capture_error = not isinstance(err, task_func.silenced_exceptions)
                if retry:
                    if retry.should_retry(inflight.activation.retry_state, err):
                        logger.info(
                            "taskworker.task.retry",
                            extra={
                                "namespace": inflight.activation.namespace,
                                "taskname": inflight.activation.taskname,
                                "processing_pool": processing_pool_name,
                                "error": str(err),
                            },
                        )
                        next_state = TASK_ACTIVATION_STATUS_RETRY
                    elif retry.max_attempts_reached(inflight.activation.retry_state):
                        with sentry_sdk.isolation_scope() as scope:
                            retry_error = NoRetriesRemainingError(
                                f"{inflight.activation.taskname} has consumed all of its retries"
                            )
                            retry_error.__cause__ = err
                            scope.fingerprint = [
                                "taskworker.no_retries_remaining",
                                inflight.activation.namespace,
                                inflight.activation.taskname,
                            ]
                            scope.set_transaction_name(inflight.activation.taskname)
                            sentry_sdk.capture_exception(retry_error)
                            # Emit a structured worker log without logger.exception so this
                            # branch does not create a second Sentry error event.
                            _log_task_retry_exhausted(
                                inflight.activation, err, processing_pool_name
                            )
                        # In this branch, all exceptions should be either
                        #  captured or silenced.
                        captured_error = True

                if (
                    should_capture_error
                    and not captured_error
                    and next_state != TASK_ACTIVATION_STATUS_RETRY
                ):
                    _log_task_failed(inflight.activation, err, processing_pool_name)
            finally:
                _adjust_busy(busy_counter, -1)

            clear_current_task()
            processed_task_count += 1

            task_produced_futures = TaskProducer.collect_futures()
            # If the task function itself failed, we don't need to await any
            # producer futures since it'll be retried anyways
            if next_state != TASK_ACTIVATION_STATUS_COMPLETE:
                task_produced_futures = {}

            if len(task_produced_futures) == 0:
                _task_execution_complete(
                    inflight,
                    next_state,
                    execution_start_time,
                    time.time(),
                    task_func,
                )
            else:
                # Place ProcessingResult immediately if we're skipping awaiting futures
                if skip_awaiting_futures:
                    _place_processing_result(
                        inflight,
                        next_state,
                        task_func,
                    )
                for name, futures in task_produced_futures.items():
                    # How many futures were produced in the executed task,
                    # tagged by producer name
                    metrics.gauge(
                        "taskworker.task.futures_produced",
                        len(futures),
                        tags={
                            "producer_name": name,
                            "processing_pool": processing_pool_name,
                            "namespace": inflight.activation.namespace,
                            "taskname": inflight.activation.taskname,
                        },
                    )
                pending_task = ActivationWithPendingFutures(
                    inflight=inflight,
                    status=next_state,
                    execution_start_time=execution_start_time,
                    futures_start_time=time.time(),
                    pending_futures=task_produced_futures,
                    task_func=task_func,
                )
                pending_task_futures.append(pending_task)

        # Once we get the shutdown signal, drain any pending futures
        _future_completion_thread.join()
        for task in pending_task_futures.copy():
            await_task_futures(task)

    def _execute_activation(
        task_func: Task[Any, Any],
        activation: TaskActivation,
        context_hooks: Sequence[ContextHook] = (),
    ) -> None:
        """Invoke a task function with the activation parameters."""
        parameters = load_parameters(activation)

        args = parameters.get("args", [])
        kwargs = parameters.get("kwargs", {})

        headers = dict(activation.headers)
        transaction = sentry_sdk.continue_trace(
            environ_or_headers=headers,
            op="queue.task.taskworker",
            name=activation.taskname,
            origin="taskworker",
        )
        sampling_context = {
            "taskworker": {
                "task": activation.taskname,
            }
        }
        with (
            metrics.track_memory_usage(
                "taskworker.worker.memory_change",
                tags={"namespace": activation.namespace, "taskname": activation.taskname},
            ),
            sentry_sdk.isolation_scope(),
            sentry_sdk.start_transaction(transaction, custom_sampling_context=sampling_context),
        ):
            transaction.set_data(
                "taskworker-task", {"args": args, "kwargs": kwargs, "id": activation.id}
            )
            task_added_time = activation.received_at.ToDatetime().timestamp()
            # latency attribute needs to be in milliseconds
            latency = (time.time() - task_added_time) * 1000

            with sentry_sdk.start_span(
                op=OP.QUEUE_PROCESS,
                name=activation.taskname,
                origin="taskworker",
            ) as span:
                span.set_data(SPANDATA.MESSAGING_DESTINATION_NAME, activation.namespace)
                span.set_data(SPANDATA.MESSAGING_MESSAGE_ID, activation.id)
                span.set_data(SPANDATA.MESSAGING_MESSAGE_RECEIVE_LATENCY, latency)
                span.set_data(
                    SPANDATA.MESSAGING_MESSAGE_RETRY_COUNT, activation.retry_state.attempts
                )
                span.set_data(SPANDATA.MESSAGING_SYSTEM, "taskworker")

                # TODO(taskworker) remove this when doing cleanup
                # The `__start_time` parameter is spliced into task parameters by
                # sentry.celery.SentryTask._add_metadata and needs to be removed
                # from kwargs like sentry.tasks.base.instrumented_task does.
                if "__start_time" in kwargs:
                    kwargs.pop("__start_time")

                try:
                    with contextlib.ExitStack() as stack:
                        with metrics.timer(
                            "taskworker.worker.context_rebuild.duration",
                            tags={
                                "namespace": activation.namespace,
                                "taskname": activation.taskname,
                            },
                        ):
                            for hook in context_hooks:
                                stack.enter_context(hook.on_execute(headers))
                        if task_func.pass_headers:
                            if "headers" in kwargs:
                                raise TypeError(
                                    f"Task '{task_func.name}' has pass_headers=True, but 'headers' was passed in kwargs. "
                                    "The 'headers' parameter is injected by the worker and cannot be passed by the caller."
                                )
                            task_func(*args, headers=headers, **kwargs)
                        else:
                            task_func(*args, **kwargs)
                    transaction.set_status(SPANSTATUS.OK)
                except Exception:
                    transaction.set_status(SPANSTATUS.INTERNAL_ERROR)
                    raise

    def record_task_execution(
        activation: TaskActivation,
        status: TaskActivationStatus.ValueType,
        start_time: float,
        completion_time: float,
        processing_pool_name: str,
        taskbroker_host: str,
        futures_enqueued_time: float | None = None,
    ) -> None:
        task_added_time = activation.received_at.ToDatetime().timestamp()
        execution_duration = completion_time - start_time
        execution_latency = completion_time - task_added_time
        futures_duration = time.time() - futures_enqueued_time if futures_enqueued_time else 0

        logger.debug(
            "taskworker.task_execution",
            extra={
                "taskname": activation.taskname,
                "execution_duration": execution_duration,
                "execution_latency": execution_latency,
                "status": status_name(status),
            },
        )
        metrics.incr(
            "taskworker.worker.execute_task",
            tags={
                "namespace": activation.namespace,
                "taskname": activation.taskname,
                "status": status_name(status),
                "processing_pool": processing_pool_name,
                "taskbroker_host": taskbroker_host,
            },
        )
        metrics.distribution(
            "taskworker.worker.execution_duration",
            execution_duration,
            tags={
                "namespace": activation.namespace,
                "taskname": activation.taskname,
                "processing_pool": processing_pool_name,
                "taskbroker_host": taskbroker_host,
            },
        )
        metrics.distribution(
            "taskworker.worker.execution_latency",
            execution_latency,
            tags={
                "namespace": activation.namespace,
                "taskname": activation.taskname,
                "processing_pool": processing_pool_name,
                "taskbroker_host": taskbroker_host,
            },
        )
        if futures_duration != 0:
            metrics.distribution(
                "taskworker.worker.future_completion_duration",
                futures_duration,
                tags={
                    "namespace": activation.namespace,
                    "taskname": activation.taskname,
                    "processing_pool": processing_pool_name,
                    "taskbroker_host": taskbroker_host,
                },
            )
        # Latency between task execution start and all producer futures completing
        # (i.e. how long it took to put the task in the processed_tasks queue)
        metrics.distribution(
            "taskworker.worker.e2e_latency",
            (execution_duration + futures_duration),
            tags={
                "namespace": activation.namespace,
                "taskname": activation.taskname,
                "processing_pool": processing_pool_name,
                "taskbroker_host": taskbroker_host,
            },
        )

        namespace = app.get_namespace(activation.namespace)
        metrics.incr(
            "taskworker.cogs.usage",
            value=int(execution_duration * 1000),
            tags={"feature": namespace.app_feature},
        )

        if (
            "sentry-monitor-check-in-id" in activation.headers
            and "sentry-monitor-slug" in activation.headers
        ):
            monitor_status = MonitorStatus.ERROR
            if status == TASK_ACTIVATION_STATUS_COMPLETE:
                monitor_status = MonitorStatus.OK

            capture_checkin(
                monitor_slug=activation.headers["sentry-monitor-slug"],
                check_in_id=activation.headers["sentry-monitor-check-in-id"],
                duration=execution_duration,
                status=monitor_status,
            )

    def _place_processing_result(
        inflight: InflightTaskActivation,
        next_state: TaskActivationStatus.ValueType,
        task_func: Task[Any, Any] | None,
    ) -> None:
        with metrics.timer(
            "taskworker.worker.processed_tasks.put.duration",
            tags={
                "processing_pool": processing_pool_name,
            },
        ):
            if task_func and task_func.retry and next_state == TASK_ACTIVATION_STATUS_RETRY:
                processed_tasks.put(
                    ProcessingResult(
                        task_id=inflight.activation.id,
                        status=next_state,
                        host=inflight.host,
                        receive_timestamp=inflight.receive_timestamp,
                        # Send max_attempts and delay_on_retry if this is a retry.
                        # Don't send it on every task as this codepath is relatively
                        # unoptimized on the broker side.
                        max_attempts=(
                            task_func.retry._times + 1
                            if task_func.retry and next_state == TASK_ACTIVATION_STATUS_RETRY
                            else None
                        ),
                        delay_on_retry=(
                            task_func.retry._delay
                            if task_func.retry and next_state == TASK_ACTIVATION_STATUS_RETRY
                            else None
                        ),
                    )
                )
            else:
                processed_tasks.put(
                    ProcessingResult(
                        task_id=inflight.activation.id,
                        status=next_state,
                        host=inflight.host,
                        receive_timestamp=inflight.receive_timestamp,
                    )
                )

    def _task_execution_complete(
        inflight: InflightTaskActivation,
        next_state: TaskActivationStatus.ValueType,
        execution_start_time: float,
        execution_end_time: float,
        task_func: Task[Any, Any] | None,
        futures_start_time: float | None = None,
        passthrough: bool = False,
    ) -> None:
        # If passthrough is enabled, we already placed a ProcessingResult
        # as soon as the task function finished execution
        if not passthrough:
            _place_processing_result(
                inflight,
                next_state,
                task_func,
            )
        record_task_execution(
            inflight.activation,
            next_state,
            execution_start_time,
            execution_end_time,
            processing_pool_name,
            inflight.host,
            futures_start_time,
        )

    # Signal that this child has finished warmup and ready to consume tasks. The parent uses this
    # to gate the gRPC SERVING health signal. Monotonic by design
    if ready_counter is not None:
        with ready_counter.get_lock():
            ready_counter.value += 1

    # Run the worker loop
    run_worker(
        child_tasks,
        processed_tasks,
        shutdown_event,
        max_task_count,
        processing_pool_name,
        process_type,
        skip_awaiting_futures,
    )
