[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["integration_tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
