apiVersion: v1
kind: Service
metadata:
  name: queue-bridge
  namespace: taskbroker-testing
spec:
  type: ClusterIP
  selector:
    app: queue-bridge
  ports:
    - name: grpc
      port: 50060
      targetPort: grpc
