# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: queue_bridge.proto
# Protobuf: checked in for prototype; must match `protobuf<6` (sentry-protos).
# If you regener with protoc 6.x, remove the runtime version check or pin protobuf>=6.
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12queue_bridge.proto\x12\x0bqueuebridge\"&\n\x0bPollRequest\x12\x17\n\x0fpoll_timeout_ms\x18\x01 \x01(\x05\"\x87\x01\n\x0cPollResponse\x12\r\n\x05\x65mpty\x18\x01 \x01(\x08\x12\x13\n\x0b\x64\x65livery_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x13\n\x0b\x62ridge_host\x18\x04 \x01(\t\x12\x13\n\x0btotal_polls\x18\x05 \x01(\x04\x12\x18\n\x10total_deliveries\x18\x06 \x01(\x04\"\x7f\n\x0f\x43ompleteRequest\x12\x13\n\x0b\x64\x65livery_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x19\n\x11\x61\x63tivation_status\x18\x03 \x01(\x05\x12\x12\n\nfetch_next\x18\x04 \x01(\x08\x12\x17\n\x0fpoll_timeout_ms\x18\x05 \x01(\x05\"\x82\x01\n\x10\x43ompleteResponse\x12\x10\n\x08has_next\x18\x01 \x01(\x08\x12\x18\n\x10next_delivery_id\x18\x02 \x01(\t\x12\x14\n\x0cnext_payload\x18\x03 \x01(\x0c\x12\x13\n\x0b\x62ridge_host\x18\x04 \x01(\t\x12\x17\n\x0ftotal_completes\x18\x05 \x01(\x04\"\x0e\n\x0c\x43heckRequest\".\n\rCheckResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xd3\x01\n\x0bQueueBridge\x12;\n\x04Poll\x12\x18.queuebridge.PollRequest\x1a\x19.queuebridge.PollResponse\x12G\n\x08\x43omplete\x12\x1c.queuebridge.CompleteRequest\x1a\x1d.queuebridge.CompleteResponse\x12>\n\x05\x43heck\x12\x19.queuebridge.CheckRequest\x1a\x1a.queuebridge.CheckResponseB\x14\n\x10io.sentry.kqueueP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020io.sentry.kqueueP\001'
  _globals['_POLLREQUEST']._serialized_start=35
  _globals['_POLLREQUEST']._serialized_end=73
  _globals['_POLLRESPONSE']._serialized_start=76
  _globals['_POLLRESPONSE']._serialized_end=211
  _globals['_COMPLETEREQUEST']._serialized_start=213
  _globals['_COMPLETEREQUEST']._serialized_end=340
  _globals['_COMPLETERESPONSE']._serialized_start=343
  _globals['_COMPLETERESPONSE']._serialized_end=473
  _globals['_CHECKREQUEST']._serialized_start=475
  _globals['_CHECKREQUEST']._serialized_end=489
  _globals['_CHECKRESPONSE']._serialized_start=491
  _globals['_CHECKRESPONSE']._serialized_end=537
  _globals['_QUEUEBRIDGE']._serialized_start=540
  _globals['_QUEUEBRIDGE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
