# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import queue_bridge_pb2 as queue__bridge__pb2

# Prototype: gRPC 1.80+ codegen embeds a runtime version check; our dependency is
# grpcio<1.80. That check is omitted so images work without re-running protoc.

class QueueBridgeStub(object):
    """Queue bridge backed by org.apache.kafka.clients.consumer.KafkaShareConsumer (Kafka 4.2+).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Poll = channel.unary_unary(
                '/queuebridge.QueueBridge/Poll',
                request_serializer=queue__bridge__pb2.PollRequest.SerializeToString,
                response_deserializer=queue__bridge__pb2.PollResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/queuebridge.QueueBridge/Complete',
                request_serializer=queue__bridge__pb2.CompleteRequest.SerializeToString,
                response_deserializer=queue__bridge__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/queuebridge.QueueBridge/Check',
                request_serializer=queue__bridge__pb2.CheckRequest.SerializeToString,
                response_deserializer=queue__bridge__pb2.CheckResponse.FromString,
                _registered_method=True)


class QueueBridgeServicer(object):
    """Queue bridge backed by org.apache.kafka.clients.consumer.KafkaShareConsumer (Kafka 4.2+).
    """

    def Poll(self, request, context):
        """Returns one acquired record or empty. After a non-empty Poll, the bridge
        does not call Kafka poll() again until Complete for that delivery_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Ack the delivery and commit; optionally block for one more Kafka record (fetch_next).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Lightweight readiness for k8s; does not require Kafka in the first version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Poll': grpc.unary_unary_rpc_method_handler(
                    servicer.Poll,
                    request_deserializer=queue__bridge__pb2.PollRequest.FromString,
                    response_serializer=queue__bridge__pb2.PollResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=queue__bridge__pb2.CompleteRequest.FromString,
                    response_serializer=queue__bridge__pb2.CompleteResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=queue__bridge__pb2.CheckRequest.FromString,
                    response_serializer=queue__bridge__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queuebridge.QueueBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('queuebridge.QueueBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueBridge(object):
    """Queue bridge backed by org.apache.kafka.clients.consumer.KafkaShareConsumer (Kafka 4.2+).
    """

    @staticmethod
    def Poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queuebridge.QueueBridge/Poll',
            queue__bridge__pb2.PollRequest.SerializeToString,
            queue__bridge__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queuebridge.QueueBridge/Complete',
            queue__bridge__pb2.CompleteRequest.SerializeToString,
            queue__bridge__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queuebridge.QueueBridge/Check',
            queue__bridge__pb2.CheckRequest.SerializeToString,
            queue__bridge__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
